### ISSUE TITLE
Failure to link two sides

### ISSUE THREAD

**Issue by LaPingvino** [ipfs-shipyard/peerpad#122]
I tested with Iran and inside my own country of the Netherlands, and the typed text doesn't arrive on the other side. Also when I write locally, it has a noticeable lag of sometimes more than a minute and sometimes necessitating a full refresh of the page to see the contents.

**Comment by pgte** [comment]
@LaPingvino There were some sync issues that I think got solved recently.
Just deployed a new version that should fix this.
Do you mind trying again?

**Comment by LaPingvino** [comment]
I tried again, it works better, but still not completely reliable :( We got contact going at least, and a working connection with live typing, but it seems to always only work in one direction somehow...
