### ISSUE TITLE
Uncaught Error: no protocol with name: p2p-webrtc-star

### ISSUE THREAD

**Issue by spaceywolfi** [ipfs-shipyard/peerpad#23]
Uncaught Error: no protocol with name: p2p-webrtc-star

**Comment by diasdavid** [comment]
Thanks for reporting @spaceywolfi 

@pgte have you released a version with latest js-ipfs? This shouldn't be an issue.

**Comment by pgte** [comment]
@spaceywolfi Should be fixed on latest, which uses peerpad-core v0.2, which uses IPFS 0.26, where this shouldn't happen any more :)
Please reopen if this is not the case.
Thank you!

**Comment by spaceywolfi** [comment]
@pgte 

 still get the same error on chrome :/

Also I have been getting this error log on firefox:

```
OpenError: The operation failed for reasons unrelated to the database itself and not covered by any other error code.
./node_modules/errno/custom.js
node_modules/errno/custom.js:22
__webpack_require__
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:669
fn
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:87
./node_modules/errno/errno.js
node_modules/errno/errno.js:312
__webpack_require__
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:669
fn
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:87
./node_modules/level-errors/errors.js
node_modules/level-errors/errors.js:7
__webpack_require__
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:669
fn
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:87
./node_modules/level-iterator-stream/index.js
node_modules/level-iterator-stream/index.js:4
__webpack_require__
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:669
fn
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:87
./node_modules/levelup/lib/levelup.js/<
node_modules/levelup/lib/levelup.js:13
./node_modules/levelup/lib/levelup.js
node_modules/levelup/lib/levelup.js:1
__webpack_require__
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:669
fn
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:87
./node_modules/datastore-level/src/index.js/<
node_modules/datastore-level/src/index.js:7
./node_modules/datastore-level/src/index.js
node_modules/datastore-level/src/index.js:1
__webpack_require__
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:669
fn
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:87
./node_modules/ipfs-repo/src/default-options-browser.js
node_modules/ipfs-repo/src/default-options-browser.js:7
__webpack_require__
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:669
fn
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:87
./node_modules/ipfs-repo/src/index.js/<
node_modules/ipfs-repo/src/index.js:16
./node_modules/ipfs-repo/src/index.js
node_modules/ipfs-repo/src/index.js:1
__webpack_require__
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:669
fn
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:87
./node_modules/ipld-resolver/src/index.js/<
node_modules/ipld-resolver/src/index.js:7
./node_modules/ipld-resolver/src/index.js
node_modules/ipld-resolver/src/index.js:1
__webpack_require__
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:669
fn
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:87
./node_modules/ipfs/src/core/index.js/<
node_modules/ipfs/src/core/index.js:4
./node_modules/ipfs/src/core/index.js
node_modules/ipfs/src/core/index.js:1
__webpack_require__
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:669
fn
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:87
./node_modules/peerpad-core/src/backend/ipfs.js
node_modules/peerpad-core/src/backend/ipfs.js:3
__webpack_require__
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:669
fn
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:87
./node_modules/peerpad-core/src/index.js
node_modules/peerpad-core/src/index.js:4
__webpack_require__
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:669
fn
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:87
./src/components/App.js
http://localhost:3000/static/js/main.bundle.js:238060:71
__webpack_require__
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:669
fn
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:87
./src/index.js
http://localhost:3000/static/js/main.bundle.js:239667:74
__webpack_require__
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:669
fn
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:87
[3]
http://localhost:3000/static/js/main.bundle.js:239760:18
__webpack_require__
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:669
(anonymous function)
/home/wolfi/academy/peerpad/webpack/bootstrap 9d8012041852f6860885:715
(anonymous function)
http://localhost:3000/static/js/main.bundle.js:1:11
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
```

PS: i do not have the rights to reopen the issue

**Comment by diasdavid** [comment]
@spaceywolfi try clearing the storage for the application in chrome. You see this issue because your browser has a old IPFS repo.

**Comment by spaceywolfi** [comment]
@diasdavid ah yes this solved the problem in chrome.

It still doesnt work on firefox, maybe thats a new issue?
